SHInc.UI/Controllers/AlignmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SHInc.DATA;

namespace SHInc.UI.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AlignmentsController : Controller
    {
        private SuperHeroesIncEntities db = new SuperHeroesIncEntities();

        // GET: Alignments
        public ActionResult Index()
        {
            return View(db.Alignments.ToList());
        }

        // GET: Alignments/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alignment alignment = db.Alignments.Find(id);
            if (alignment == null)
            {
                return HttpNotFound();
            }
            return View(alignment);
        }

        // GET: Alignments/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Alignments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AlignmentID,AlignmentName")] Alignment alignment)
        {
            if (ModelState.IsValid)
            {
                db.Alignments.Add(alignment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(alignment);
        }

        // GET: Alignments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alignment alignment = db.Alignments.Find(id);
            if (alignment == null)
            {
                return HttpNotFound();
            }
            return View(alignment);
        }

        // POST: Alignments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AlignmentID,AlignmentName")] Alignment alignment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(alignment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(alignment);
        }

        // GET: Alignments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alignment alignment = db.Alignments.Find(id);
            if (alignment == null)
            {
                return HttpNotFound();
            }
            return View(alignment);
        }

        // POST: Alignments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Alignment alignment = db.Alignments.Find(id);
            db.Alignments.Remove(alignment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SHInc.UI/Controllers/CharactersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SHInc.DATA;

namespace SHInc.UI.Controllers
{
    [Authorize(Roles = "Admin, SuperHero")]
    public class CharactersController : Controller
    {
        private SuperHeroesIncEntities db = new SuperHeroesIncEntities();

        // GET: Characters
        public ActionResult Index()
        {
            var characters = db.Characters.Include(c => c.Alignment1);
            return View(characters.ToList());
        }

        // GET: Characters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // GET: Characters/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            ViewBag.Alignment = new SelectList(db.Alignments, "AlignmentID", "AlignmentName");
            return View();
        }

        // POST: Characters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Create([Bind(Include = "ID,Alias,FullName,Alignment,Origin")] Character character)
        {
            if (ModelState.IsValid)
            {
                db.Characters.Add(character);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Alignment = new SelectList(db.Alignments, "AlignmentID", "AlignmentName", character.Alignment);
            return View(character);
        }

        // GET: Characters/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            ViewBag.Alignment = new SelectList(db.Alignments, "AlignmentID", "AlignmentName", character.Alignment);
            return View(character);
        }

        // POST: Characters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit([Bind(Include = "ID,Alias,FullName,Alignment,Origin")] Character character)
        {
            if (ModelState.IsValid)
            {
                db.Entry(character).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Alignment = new SelectList(db.Alignments, "AlignmentID", "AlignmentName", character.Alignment);
            return View(character);
        }

        // GET: Characters/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Character character = db.Characters.Find(id);
            if (character == null)
            {
                return HttpNotFound();
            }
            return View(character);
        }

        // POST: Characters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Character character = db.Characters.Find(id);
            db.Characters.Remove(character);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SHInc.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Super Hero Inc., superhero, citizen safety, drop crime rates, villain">
    <title>@ViewBag.Title | Super Heroes, Inc</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500italic,500,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <!-- Bootstrap -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="~/Content/font-awesome.min.css">
    <!-- MaterialCSS -->
    <link rel="stylesheet" href="~/Content/material.min.css">
    <!-- RipplesCSS -->
    <link rel="stylesheet" href="~/Content/ripples.min.css">

    <!-- ThemeCSS & Responsive CSS -->
    <link rel="stylesheet" href="~/Content/style.css">
    <link rel="stylesheet" href="~/Content/responsive.css">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->



</head>
<body>
    <header class="header">
        <div data-velocity="-.4" id="particles" class="header-bg"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="social-links">
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-facebook"></i> <div class="ripple-wrapper"></div></a>
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-twitter"></i> <div class="ripple-wrapper"></div></a>
                        <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-instagram"></i> <div class="ripple-wrapper"></div></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="site-title-table">
            <div class="site-title-tablecell">
                <div class="slide-text">
                    <h2><span>S</span>uper<span> H</span>eroes, <span>I</span>nc.</h2>
                </div>
            </div>
        </div>
    </header>
    <section class="maincontent-wrap">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="maincotnent shadow-z-1">
                        <div class="mainmenu">
                            <div class="navbar navbar-nobg">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <div class="navbar-collapse collapse">
                                    <div>@Html.Partial("_LoginPartial")</div>
                                    <ul class="nav navbar-nav">
                                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                                        <li>@Html.ActionLink("Programs/Services", "Programs", "Home")</li>
                                        @if (Request.IsAuthenticated && (User.IsInRole("Admin") || User.IsInRole("SuperHero")))
                                        {
                                            <li>@Html.ActionLink("Character Database", "Index", "Characters")</li> }

                                        @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                                        {
                                            <li>@Html.ActionLink("Alignment", "Index", "Alignments")</li>
                                            <li>@Html.ActionLink("RolesAdmin", "Index", "RolesAdmin")</li>
                                            <li>@Html.ActionLink("UsersAdmin", "Index", "UsersAdmin")</li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>

                        <div class="container body-content">
                            @RenderBody()
                            <div class="bottom-padding"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-5 col-md-6 col-lg-offset-1">
                    <div class="footer-wid">
                        <h2 class="wid-title">A<span>vengers</span></h2>
                        <p>
                            Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis
                            nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan,
                        </p>
                    </div>
                </div>
                <div class="col-lg-5 col-md-6">
                    <div class="footer-wid">
                        <h2 class="wid-title">Newsletter</h2>
                        <p>Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.</p>

                        <div class="newsletter-form">
                            <form action="index.html">
                                <div class="row">
                                   <input class="shadow-z-1" type="email" placeholder="Your Email address">
                                   <a class="btn btn-material-red" href="javascript:void(0)">Subscribe Now!</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="footer-bottom">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-1">
                            <div class="copyright-text">
                                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
                            </div>
                        </div>
                        <div class="col-md-2">
                            <div class="social-links footer-social-links">
                                <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-facebook"></i> <div class="ripple-wrapper"></div></a>
                                <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-twitter"></i> <div class="ripple-wrapper"></div></a>
                                <a class="btn social-link" href="javascript:void(0)"><i class="fa fa-instagram"></i><div class="ripple-wrapper"></div></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("scripts", required: false)
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    @*<script src="~/Scripts/vendor/jquery-1.11.2.min.js"></script>*@
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/material.min.js"></script>
    <script src="~/Scripts/ripples.min.js"></script>
    <script src="~/Scripts/jquery.scrolly.js"></script>
    <script src="~/Scripts/jquery.particleground.min.js"></script>
    <script src="~/Scripts/main.js"></script>
    <link href="~/Calendar/fullcalendar.min.css" rel="stylesheet" />
    <script src="~/Calendar/jquery.min.js"></script>
    <script src="~/Calendar/moment.min.js"></script>
    <script src="~/Calendar/fullcalendar.min.js"></script>
    @RenderSection("calendar", false)
</body>
</html>